[toolchain]

[features]
resolution = true
skip-lint = false 

[programs.devnet]
marketplace = "HtQwAN1WeyKCrLkadB3rTNxZt7hmVkGB797Njz1m19xg"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
